
"""
src/visualization/plot.py

All plotting utilities for:
  "Actor-critic Deep-hedging under Time-consistent Dynamic Risk"

All functions that previously called env.simulate_batch() now load from
pre-saved tensors generated by scripts/generate_data.py.

Data layout expected at data_dir (default "content/data"):
    <data_dir>/<alpha_label>/<scoring_key>/
        states.npy, actions.npy, log_probs.npy, costs.npy,
        portfolio_values.npy, deriv_prices.npy, PnL.npy,
        terminal_pnl.npy, S_paths.npy, h_paths.npy, R_paths.npy
    <data_dir>/<alpha_label>/static/
        (same files)

Public API
----------
plot_portfolio_delta(alpha_label, data_dir, env, save_dir)
plot_g2_functions(save_dir)
plot_pnl_distributions(alpha_label, data_dir, save_dir)
plot_scoring_curvature(score_fn, save_dir)
plot_extreme_trajectory(alpha_label, data_dir, env, save_dir)
plot_dynamic_risk_comparison(alpha_label, data_dir, all_models, all_norms,
                             env, CriticCVaR, nested_ckpt_static_path,
                             nested_ckpt_dynamic_path, save_dir)
plot_validation_risk(log_files, save_dir)
plot_initial_dynamic_cvar(log_files, alpha_label, data_dir, env, CriticCVaR,
                          nested_ckpt_shift_path, nested_ckpt_noshift_path,
                          actor_noshift_ckpt_path, Actor, save_dir)
plot_actor_critic_loss(log_files, save_dir)
plot_mean_action(log_files, save_dir)
"""

import os
import re
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import matplotlib as mpl
from matplotlib.colors import Normalize
from scipy.stats import gaussian_kde
import torch


# ---------------------------------------------------------------------------
# Shared constants
# ---------------------------------------------------------------------------

SCORING_DISPLAY = {
    "arcsin":   r"$G(x) = \arcsin\!\left(\frac{1}{x+1}\right)$",
    "arcsinh":  r"$G(x) = -\mathrm{arcsinh}(x)$",
    "arctan":   r"$G(x) = -\arctan(x)$",
    "log":      r"$G(x) = -\log(x)$",
    "power03":  r"$G(x) = -x^{0.3}$",
    "rational": r"$G(x) = -\dfrac{x}{1+x}$",
}

SCORING_KEYS = ["arcsin", "arcsinh", "arctan", "log", "power03", "rational"]

_SCORING_COLORS = [
    "#4C8FE8", "#D4537E", "#1D9E75",
    "#7F77DD", "#BA7517", "#F5A623",
]
SCORING_COLOR = dict(zip(SCORING_KEYS, _SCORING_COLORS))
STATIC_COLOR  = "#E05CB8"
ASSET_NAMES   = ["JPM", "BAC", "WFC", "C"]


def _load(data_dir, alpha_label, key, filename):
    """Load a single .npy file for a given actor key."""
    return np.load(os.path.join(data_dir, alpha_label, key, filename))


def _style_ax(ax):
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines[["left", "bottom"]].set_color("#cccccc")
    ax.set_facecolor("#f7f7f7")
    ax.grid(False)
    ax.set_axisbelow(False)
    ax.tick_params(colors="#444444")


def _save(fig, save_dir, stem, dpi_pdf=500, dpi_png=150):
    os.makedirs(save_dir, exist_ok=True)
    for ext, dpi in [("pdf", dpi_pdf), ("png", dpi_png)]:
        path = os.path.join(save_dir, f"{stem}.{ext}")
        fig.savefig(path, bbox_inches="tight", dpi=dpi)
        print(f"Saved -> {path}")


# ---------------------------------------------------------------------------
# 1. G(x) functions  — no data needed
# ---------------------------------------------------------------------------

def plot_g2_functions(save_dir: str = ".") -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    x = np.linspace(0.01, 5, 500)
    funcs = {
        r"Logarithmic:  $-\log(x)$":                               -np.log(x),
        r"Fractional Power:  $-x^{0.3}$":                          -x ** 0.3,
        r"Arctangent:  $-\arctan(x)$":                             -np.arctan(x),
        r"Arcsinh:  $-\mathrm{arcsinh}(x)$":                       -np.arcsinh(x),
        r"Rational:  $-\frac{x}{1+x}$":                            -x / (1 + x),
        r"Arcsin:  $\arcsin\!\left(\frac{1}{x+1}\right)$":         np.arcsin(np.clip(1 / (x + 1), -1, 1)),
    }

    fig, ax = plt.subplots(figsize=(10, 5))
    for (name, y), color in zip(funcs.items(), _SCORING_COLORS):
        ax.plot(x, y, lw=1.8, color=color, label=name, alpha=0.9)

    ax.set_xlabel(r"$x$",    fontsize=12, color="#444444")
    ax.set_ylabel(r"$G(x)$", fontsize=12, color="#444444")
    ax.set_xlim(0, 5)
    ax.set_ylim(-4, 5)
    ax.axhline(0, color="#cccccc", lw=0.8, zorder=0)
    _style_ax(ax)
    ax.legend(frameon=False, fontsize=10, loc="upper right", labelcolor="#444444")

    plt.tight_layout()
    _save(fig, save_dir, "g2_functions")
    plt.show()


# ---------------------------------------------------------------------------
# 2. Portfolio delta scatter
# ---------------------------------------------------------------------------

def plot_portfolio_delta(
    alpha_label: str = "alpha95",
    data_dir:    str = "content/data",
    env                = None,
    save_dir:    str = ".",
    n_paths:     int = 1000,
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    T       = env.T_days
    weights = env.basket_weights.cpu().numpy()

    norm      = Normalize(vmin=0, vmax=T - 1)
    t_indices = np.repeat(np.arange(T), n_paths)

    # Load shared S_paths ONCE — same paths for all actors
    shared_S = np.load(os.path.join(data_dir, alpha_label, "_shared_paths", "S_paths.npy"))
    basket_moneyness = (shared_S[:n_paths, :T, :] * weights).sum(axis=-1) / env.K  # [n, T]
    del shared_S

    fig, axes = plt.subplots(
        2, 3, figsize=(12, 7),
        sharex=True, sharey=True,
        constrained_layout=True,
    )

    for idx, sk in enumerate(SCORING_KEYS):
        ax = axes.flat[idx]

        actions_np = np.load(
            os.path.join(data_dir, alpha_label, "_shared_paths", sk, "actions.npy")
        )[:, :n_paths, :]  # [T, n, 4]
        port_delta = (actions_np * weights).sum(axis=-1)  # [T, n]

        x = basket_moneyness.T.ravel()  # [T, n] -> T*n
        y = port_delta.ravel()          # [T, n] -> T*n

        ax.scatter(x, y, s=0.5, alpha=0.3,
                   c=t_indices, cmap="viridis", norm=norm,
                   rasterized=True, linewidths=0)

        ax.set_title(SCORING_DISPLAY[sk], fontsize=12, color="#444444")
        _style_ax(ax)
        ax.set_axisbelow(True)
        if idx in [0, 3]:
            ax.set_ylabel("Weighted Aggregate Position", fontsize=12, color="#444444")
        if idx in [3, 4, 5]:
            ax.set_xlabel("Moneyness", fontsize=12, color="#444444")

    _save(fig, save_dir, "portfolio_delta_plot")
    plt.show()

# ---------------------------------------------------------------------------
# 3. PnL distributions
# ---------------------------------------------------------------------------

def plot_pnl_distributions(
    alpha_label:    str   = "alpha95",
    data_dir:       str   = "content/data",
    save_dir:       str   = ".",
    tail_prob:      float = 0.05,
    scoring_labels: list  = None,
) -> None:
    """
    KDE + histogram of normalised terminal hedging loss for all scoring functions
    and the static baseline. Loads terminal_pnl.npy and deriv_prices.npy
    from pre-saved data.
    """
    mpl.rcParams.update({
        "font.family":      "sans-serif",
        "axes.titlesize":   14,
        "axes.labelsize":   12,
        "xtick.labelsize":  10,
        "ytick.labelsize":  10,
        "legend.fontsize":  9,
    })

    if scoring_labels is None:
        scoring_labels = ["rational", "arcsinh", "arctan", "arcsin", "power03", "log"]

    drm_colors = [
        _SCORING_COLORS[SCORING_KEYS.index(sl)] if sl in SCORING_KEYS else "#888888"
        for sl in scoring_labels
    ]

    def _load_pnl(key):
        pnl = _load(data_dir, alpha_label, key, "terminal_pnl.npy")
        d0  = _load(data_dir, alpha_label, key, "deriv_prices.npy")[:, 0]
        return -pnl / d0   # negate: positive = loss, normalised by initial option price

    def _cvar(losses):
        # losses already positive = bad, take upper tail
        sorted_losses = np.sort(losses)[::-1]
        n = max(1, int(len(sorted_losses) * tail_prob))
        return sorted_losses[:n].mean()

    drm_data    = {sl: _load_pnl(sl) for sl in scoring_labels}
    static_data = _load_pnl("static")

    all_arrays = list(drm_data.values()) + [static_data]
    x_min  = min(np.percentile(a, 0.1)  for a in all_arrays)
    x_max  = max(np.percentile(a, 99.9) for a in all_arrays)
    x_grid = np.linspace(x_min, x_max, 1000)

    fig, ax = plt.subplots(figsize=(14, 6), dpi=180)
    plt.subplots_adjust(left=0.25)

    for sl, color in zip(scoring_labels, drm_colors):
        arr      = drm_data[sl]
        cvar_val = -1 * _cvar(arr)
        mean_val = np.mean(arr)

        ax.hist(-1 * arr, bins=100, range=(x_min, x_max),
                density=True, color=color, alpha=0.18, linewidth=0)
        ax.plot(x_grid, gaussian_kde(-1 * arr)(x_grid),
                color=color, linewidth=1.8, label=sl)
        ax.axvline(cvar_val, color=color, linestyle="--", linewidth=1.0, alpha=0.75)
        ax.axvline(mean_val, color=color, linestyle=":",  linewidth=1.2, alpha=0.90)

    cvar_val = -1 * _cvar(static_data)
    mean_val = np.mean(static_data)
    ax.hist(-1 *  static_data, bins=100, range=(x_min, x_max),
            density=True, color=STATIC_COLOR, alpha=0.15, linewidth=0)
    ax.plot(x_grid, gaussian_kde(-1 * static_data)(x_grid),
            color=STATIC_COLOR, linewidth=2.2, label="static")
    ax.axvline(cvar_val, color=STATIC_COLOR, linestyle="--", linewidth=1.2)
    ax.axvline(mean_val, color=STATIC_COLOR, linestyle=":",  linewidth=1.2)
    _style_ax(ax)
    ax.set_xlabel(r"Normalized Terminal Hedging Error")
    ax.set_ylabel("Density")
    ax.legend(loc="upper right", frameon=False)

    plt.tight_layout()
    _save(fig, save_dir, "pnl_distributions")
    plt.show()


# ---------------------------------------------------------------------------
# 4. Scoring curvature  — generates its own synthetic data, no paths needed
# ---------------------------------------------------------------------------

def plot_scoring_curvature(
    score_fn,
    save_dir:  str   = ".",
    N:         int   = 10_000,
    half:      float = 2.0,
    alpha_ds:  float = 0.95,
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    np.random.seed(42)
    colors = ["#378ADD", "#D85A30", "#1D9E75", "#7F77DD", "#BA7517", "#D4537E"]

    def _score_np(a1, a2, y, alpha, C):
        return score_fn(
            torch.tensor(a1, dtype=torch.float32),
            torch.tensor(a2, dtype=torch.float32),
            torch.tensor(y,  dtype=torch.float32),
            alpha, C,
        ).numpy()

    alphas = [0.10, 0.30, 0.50, 0.70, 0.85, 0.95]
    y_base = np.random.normal(0, 1, N)
    C_base = abs(y_base.min())

    target_var = np.quantile(np.random.normal(0, 1, N), alpha_ds)
    fixed_var_datasets = {}
    for sigma in [0.5, 0.8, 1.0, 1.5, 2.0, 3.0]:
        y  = np.random.normal(0, sigma, N)
        y += target_var - np.quantile(y, alpha_ds)
        ev = np.quantile(y, alpha_ds)
        ec = y[y >= ev].mean()
        fixed_var_datasets[f"CVaR={ec:.2f}"] = (y, ev, ec)

    target_cvar = 1.8
    fixed_cvar_datasets = {}
    for shift in [-2.5, -1.5, -0.5, 0.5, 1.5, 2.5]:
        y      = np.random.normal(shift, 1, N)
        ev     = np.quantile(y, alpha_ds)
        ec_raw = y[y >= ev].mean()
        mask   = y >= ev
        y[mask] = ev + (y[mask] - ev) * (target_cvar - ev) / max(ec_raw - ev, 1e-6)
        ev = np.quantile(y, alpha_ds)
        ec = y[y >= ev].mean()
        fixed_cvar_datasets[f"VaR={ev:.2f}"] = (y, ev, ec)

    y1 = np.random.normal(5,  1, N)
    y2 = np.random.normal(25, 1, N)

    fig, axes = plt.subplots(3, 2, figsize=(13, 13))

    for alpha, color in zip(alphas, colors):
        ev = np.quantile(y_base, alpha)
        ec = y_base[y_base >= ev].mean()

        grid = np.linspace(ev - half, ev + half, 300)
        sc   = np.array([_score_np(np.full(N, a), np.full(N, a), y_base, alpha, C_base).mean() for a in grid])
        oi   = np.argmin(sc)
        axes[0, 0].plot(grid, sc, color=color, lw=1.6, alpha=0.85, label=f"alpha={alpha:.2f}")
        axes[0, 0].scatter(grid[oi], sc[oi], color=color, s=60, zorder=5)

        grid = np.linspace(ec - half, ec + half, 300)
        sc   = np.array([_score_np(np.full(N, ev), np.full(N, a), y_base, alpha, C_base).mean() for a in grid])
        oi   = np.argmin(sc)
        axes[0, 1].plot(grid, sc, color=color, lw=1.6, alpha=0.85, label=f"alpha={alpha:.2f}")
        axes[0, 1].scatter(grid[oi], sc[oi], color=color, s=60, zorder=5)

    for (name, (y, ev, ec)), color in zip(fixed_var_datasets.items(), colors):
        C    = abs(y.min())
        grid = np.linspace(ev - half, ev + half, 300)
        sc   = np.array([_score_np(np.full(N, a), np.full(N, a), y, alpha_ds, C).mean() for a in grid])
        oi   = np.argmin(sc)
        axes[1, 0].plot(grid, sc, color=color, lw=1.6, alpha=0.85, label=name)
        axes[1, 0].scatter(grid[oi], sc[oi], color=color, s=60, zorder=5)

    for (name, (y, ev, ec)), color in zip(fixed_cvar_datasets.items(), colors):
        C    = abs(y.min())
        grid = np.linspace(ec - half, ec + half, 300)
        sc   = np.array([_score_np(np.full(N, ev), np.full(N, a), y, alpha_ds, C).mean() for a in grid])
        oi   = np.argmin(sc)
        axes[1, 1].plot(grid, sc, color=color, lw=1.6, alpha=0.85, label=name)
        axes[1, 1].scatter(grid[oi], sc[oi], color=color, s=60, zorder=5)

    rel_grid = np.linspace(-3.5, 3.5, 300)
    for y_samp, color, label in [
        (y1, "#378ADD", r"$\mathcal{N}(5,1)$"),
        (y2, "#D85A30", r"$\mathcal{N}(25,1)$"),
    ]:
        C  = abs(y_samp.min())
        ev = np.quantile(y_samp, alpha_ds)
        ec = y_samp[y_samp >= ev].mean()

        sc = np.array([_score_np(np.full(N, ev + a), np.full(N, ev + a), y_samp, alpha_ds, C).mean() for a in rel_grid])
        sc -= sc.min()
        oi  = np.argmin(sc)
        axes[2, 0].plot(rel_grid, sc, color=color, lw=1.6, alpha=0.85, label=label)
        axes[2, 0].scatter(rel_grid[oi], sc[oi], color=color, s=60, zorder=5)

        sc = np.array([_score_np(np.full(N, ev), np.full(N, ec + a), y_samp, alpha_ds, C).mean() for a in rel_grid])
        sc -= sc.min()
        oi  = np.argmin(sc)
        axes[2, 1].plot(rel_grid, sc, color=color, lw=1.6, alpha=0.85, label=label)
        axes[2, 1].scatter(rel_grid[oi], sc[oi], color=color, s=60, zorder=5)

    axes[2, 0].axvline(0, color="k", lw=0.8, linestyle="--", alpha=0.4)
    axes[2, 1].axvline(0, color="k", lw=0.8, linestyle="--", alpha=0.4)

    panel_xlabels = [
        (axes[0, 0], r"$\mathfrak{a}_1$"), (axes[0, 1], r"$\mathfrak{a}_2$"),
        (axes[1, 0], r"$\mathfrak{a}_1$"), (axes[1, 1], r"$\mathfrak{a}_2$"),
        (axes[2, 0], r"$\mathfrak{a}_1$"), (axes[2, 1], r"$\mathfrak{a}_2$"),
    ]
    for ax, xlabel in panel_xlabels:
        ax.set_xlabel(xlabel, fontsize=13, color="#444444")
        ax.set_ylabel(r"$\mathrm{s}(\mathfrak{a}_1,\mathfrak{a}_2)$", fontsize=13, color="#444444")
        _style_ax(ax)
        ax.tick_params(labelbottom=False, labelleft=False)
        ax.axhline(0, color="k", lw=0.5, alpha=0.3)
        ydata  = np.concatenate([l.get_ydata() for l in ax.lines])
        finite = ydata[np.isfinite(ydata)]
        p5, p95 = np.percentile(finite, [5, 95])
        margin  = (p95 - p5) * 0.4
        ax.set_ylim(p5 - margin, p95 + margin)

    alpha_handles = [mlines.Line2D([], [], color=c, lw=2, label=f"alpha={a:.2f}") for a, c in zip(alphas, colors)]
    axes[0, 0].legend(handles=alpha_handles, fontsize=8, frameon=False)
    axes[0, 1].legend(handles=alpha_handles, fontsize=8, frameon=False)

    for ax, ds in [(axes[1, 0], fixed_var_datasets), (axes[1, 1], fixed_cvar_datasets)]:
        handles = [mlines.Line2D([], [], color=c, lw=2, label=n) for (n, _), c in zip(ds.items(), colors)]
        ax.legend(handles=handles, fontsize=8, frameon=False)

    for ax in [axes[2, 0], axes[2, 1]]:
        ax.legend(fontsize=9, frameon=False)

    plt.tight_layout()
    _save(fig, save_dir, "scoring_curvature_full")
    plt.show()


# ---------------------------------------------------------------------------
# 5. Extreme trajectory
# ---------------------------------------------------------------------------
def plot_extreme_trajectory(
    alpha_label:    str = "alpha95",
    data_dir:       str = "content/data",
    env                 = None,
    save_dir:       str = ".",
    n_paths:        int = 1000,
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    T          = env.T_days
    timesteps  = np.arange(T)     / 252
    t_full     = np.arange(T + 1) / 252

    basket_weights = np.array([0.07690456, 0.44895452, 0.26472574, 0.20941517])
    corr_pairs  = [(i, j) for i in range(4) for j in range(i + 1, 4)]
    corr_labels = [f"{ASSET_NAMES[i]}-{ASSET_NAMES[j]}" for i, j in corr_pairs]

    colors_scoring = [
        _SCORING_COLORS[SCORING_KEYS.index(sk)] if sk in SCORING_KEYS else "#888888"
        for sk in SCORING_DISPLAY
    ]
    colors_assets = list(plt.cm.Set1(np.linspace(0, 0.8, 4)))
    colors_corr   = list(plt.cm.tab10(np.linspace(0, 1.0, 6)))

    first_sk = SCORING_KEYS[0]
    S_paths  = _load(data_dir, alpha_label, first_sk, "S_paths.npy")[:n_paths]   # [n, T+1, 4]

    basket_np  = (S_paths * basket_weights).sum(axis=-1)                          # [n, T+1]

    # Find the path with the largest total price run-up (terminal / initial)
    runup     = basket_np[:, -1] / basket_np[:, 0]
    hard_idx  = int(np.argmax(runup))
    print(f"Hard trajectory: idx={hard_idx}  run-up={runup[hard_idx]:.4f}x  "
          f"(basket start={basket_np[hard_idx, 0]:.2f}  end={basket_np[hard_idx, -1]:.2f})")

    basket_hard = basket_np[hard_idx]
    S_hard      = S_paths[hard_idx]                                               # [T+1, 4]

    h_paths  = _load(data_dir, alpha_label, first_sk, "h_paths.npy")[:n_paths]   # [n, T+1, 4]
    h_hard   = h_paths[hard_idx]                                                  # [T+1, 4]
    vol_hard = np.sqrt(252 * h_hard)

    Q_paths  = _load(data_dir, alpha_label, first_sk, "Q_paths.npy")[:n_paths]   # [n, T+1, 4, 4]
    Q_hard   = Q_paths[hard_idx]                                                  # [T+1, 4, 4]
    d_diag   = np.sqrt(np.diagonal(Q_hard, axis1=1, axis2=2))
    R_hard   = Q_hard / (d_diag[:, :, None] * d_diag[:, None, :])
    corr_hard = np.stack([R_hard[:, i, j] for i, j in corr_pairs], axis=1)       # [T+1, 6]

    all_actions  = {}
    terminal_pnl = {}

    for sk in SCORING_KEYS:
        actions = _load(data_dir, alpha_label, sk, "actions.npy")[:, :n_paths, :]       # [T, n, 4]
        portval = _load(data_dir, alpha_label, sk, "portfolio_values.npy")[:n_paths, :]  # [n, T]
        all_actions[sk]  = actions[:, hard_idx, :]                                       # [T, 4]
        terminal_pnl[sk] = float(portval[hard_idx, -1])

    actions_s = _load(data_dir, alpha_label, "static", "actions.npy")[:, :n_paths, :]
    portval_s = _load(data_dir, alpha_label, "static", "portfolio_values.npy")[:n_paths, :]
    all_actions["static"]  = actions_s[:, hard_idx, :]
    terminal_pnl["static"] = float(portval_s[hard_idx, -1])

    # ── 4×2 layout ────────────────────────────────────────────────────────
    # Rows 0–1 (top 2×2): one asset per panel, positions for all actors
    # Rows 2–3 (bottom 2×2): basket | prices | volatilities | correlations
    fig, axes = plt.subplots(4, 2, figsize=(14, 18))

    asset_axes = [axes[0, 0], axes[0, 1], axes[1, 0], axes[1, 1]]
    lower_axes = [axes[2, 0], axes[2, 1], axes[3, 0], axes[3, 1]]

    # ── Top 2×2: per-asset positions ──────────────────────────────────────
    for asset_idx, ax in enumerate(asset_axes):
        for (sk, label), color in zip(SCORING_DISPLAY.items(), colors_scoring):
            ax.plot(timesteps, all_actions[sk][:, asset_idx],
                    color=color, linewidth=1.4, alpha=0.85)
        ax.plot(timesteps, all_actions["static"][:, asset_idx],
                color="black", linewidth=2.2, linestyle="--", alpha=0.95)
        ax.set_title(ASSET_NAMES[asset_idx], fontsize=11, pad=4)
        ax.set_xlabel("Time (Years)", fontsize=9)
        ax.set_ylabel("Position", fontsize=9)
        _style_ax(ax)

    # ── Bottom 2×2: market-state panels ───────────────────────────────────
    # [2,0] Basket value
    ax = lower_axes[0]
    ax.plot(t_full, basket_hard, color="#c0392b", linewidth=1.8)
    ax.set_xlabel("Time (Years)", fontsize=9)
    ax.set_ylabel("Basket Value", fontsize=9)
    _style_ax(ax)

    # [2,1] Individual stock prices
    ax = lower_axes[1]
    for i, (name, color) in enumerate(zip(ASSET_NAMES, colors_assets)):
        ax.plot(t_full, S_hard[:, i], color=color, linewidth=1.4, label=name)
    ax.set_xlabel("Time (Years)", fontsize=9)
    ax.set_ylabel("Price", fontsize=9)
    ax.legend(fontsize=8, frameon=False)
    _style_ax(ax)

    # [3,0] Annualised volatilities
    ax = lower_axes[2]
    for i, (name, color) in enumerate(zip(ASSET_NAMES, colors_assets)):
        ax.plot(t_full, vol_hard[:, i], color=color, linewidth=1.4, label=name)
    ax.set_xlabel("Time (Years)", fontsize=9)
    ax.set_ylabel("Ann. Volatility", fontsize=9)
    ax.legend(fontsize=8, frameon=False)
    _style_ax(ax)

    # [3,1] Pairwise correlations
    ax = lower_axes[3]
    for k, (label, color) in enumerate(zip(corr_labels, colors_corr)):
        ax.plot(t_full, corr_hard[:, k], color=color, linewidth=1.2, label=label)
    ax.set_xlabel("Time (Years)", fontsize=9)
    ax.set_ylabel("Correlation", fontsize=9)
    ax.legend(fontsize=7, frameon=False, ncol=2)
    _style_ax(ax)

    # ── Shared legend (scoring functions) ─────────────────────────────────
    legend_handles = [
        mlines.Line2D([], [], color=c, lw=1.4, alpha=0.85, label=lbl)
        for (sk, lbl), c in zip(SCORING_DISPLAY.items(), colors_scoring)
    ] + [mlines.Line2D([], [], color="black", lw=2.2, linestyle="--", label="Static")]
    fig.legend(
        handles=legend_handles, loc="lower center", ncol=7,
        frameon=False, fontsize=10, bbox_to_anchor=(0.5, -0.04),
        title="Scoring Function", title_fontsize=10,
    )

    # ── Terminal P&L annotation ────────────────────────────────────────────
    pnl_parts_dynamic = [f"{lbl}: {terminal_pnl[sk]:+.4f}" for sk, lbl in SCORING_DISPLAY.items()]
    pnl_line1 = "Terminal P&L:  " + "   |   ".join(pnl_parts_dynamic[:3])
    pnl_line2 = "   |   ".join(pnl_parts_dynamic[3:]) + f"   |   Static: {terminal_pnl['static']:+.4f}"

    plt.tight_layout()
    fig.subplots_adjust(bottom=0.12)

    fig.text(
        0.5, 0.06, pnl_line1,
        ha="center", va="center", fontsize=11, color="#444444", style="italic",
    )
    fig.text(
        0.5, 0.025, pnl_line2,
        ha="center", va="center", fontsize=11, color="#444444", style="italic",
    )

    _save(fig, save_dir, "actions_hard_traj_4x2")
    plt.show()

# ---------------------------------------------------------------------------
# 6. Dynamic risk comparison
# ---------------------------------------------------------------------------


def plot_dynamic_risk_comparison(
    alpha_label:             str = "alpha95",
    data_dir:                str = "content/data",
    all_models:              dict = None,
    all_norms:               dict = None,
    env                          = None,
    CriticVaRExcess              = None,
    CriticCVaR                   = None,
    nested_ckpt_static_path: str = "NestedCritics/critic_checkpoint_static_epoch4.pt",
    nested_ckpt_dynamic_path:str = "NestedCritics/critic_checkpoint_epoch4.pt",
    save_dir:                str = ".",
    n_paths:                 int = 1000,
    risk_threshold:          int = 95,
    n_groups:                int = 18,
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    device     = env.device
    T          = env.T_days
    group_size = T // n_groups
    colors     = plt.cm.tab10(np.linspace(0, 0.6, 6))

    scoring_display = {
        "rational": "Rational", "arcsinh": "Arcsinh", "log": "Log",
        "arcsin":   "Arcsin",   "arctan":  "Arctan",  "power03": "Power",
    }

    def _load_nested(ckpt_path):
        ckpt    = torch.load(ckpt_path, map_location="cpu", weights_only=False)
        critics = torch.nn.ModuleList([
            CriticCVaR(env.state_dim, group_size, hidden_dim=64, head_dim=64, device=device)
            for _ in range(n_groups)
        ])
        for g in range(n_groups):
            critics[g].load_state_dict(ckpt["critics"][g])
            critics[g].to(device).eval()
        return critics

    nested_critics_static  = _load_nested(nested_ckpt_static_path)
    nested_critics_dynamic = _load_nested(nested_ckpt_dynamic_path)

    fig, ax = plt.subplots(figsize=(13, 4.5))
    t_axis  = np.arange(T) / 252

    # ── Dynamic CVaR from RL agent critics (CriticVaRExcess) ──────────────
    for (sk, label), color in zip(scoring_display.items(), colors):
        states_np = _load(data_dir, alpha_label, sk, "states.npy")[:, :n_paths, :]
        costs_np  = _load(data_dir, alpha_label, sk, "costs.npy")[:, :n_paths]

        raw_critics = all_models[alpha_label][sk]["critics"]
        critics = []
        for c in raw_critics:
            fresh = CriticVaRExcess(
                env.state_dim, group_size,
                head_dim_var=128, head_dim_excess=128,
            )
            fresh.load_state_dict(c.state_dict())
            fresh.to(device).eval()
            critics.append(fresh)

        b_values = all_norms[alpha_label][sk]["b_values"]
        states_t = torch.tensor(states_np, dtype=torch.float32, device=device)

        cvar_grid = np.zeros((n_paths, T))
        with torch.no_grad():
            for g in range(n_groups):
                gs, ge = g * group_size, (g + 1) * group_size
                v, e = critics[g](states_t[gs:ge])
                cvar_grid[:, gs:ge] = (
                    (v + e).squeeze(-1) + b_values[n_groups - 1 - g]
                ).T.cpu().numpy()

        ax.plot(t_axis, cvar_grid.mean(axis=0),
                label=label, color=color, linewidth=1.4, alpha=0.75, zorder=3)

    # ── Nested heuristic CVaR for static actor ─────────────────────────────
    states_s_np = _load(data_dir, alpha_label, "static", "states.npy")[:, :n_paths, :]
    states_s    = torch.tensor(states_s_np, dtype=torch.float32, device=device)

    nested_s = np.zeros((n_paths, T))
    with torch.no_grad():
        for g in range(n_groups):
            gs, ge = g * group_size, (g + 1) * group_size
            nested_s[:, gs:ge] = nested_critics_static[g](states_s[gs:ge]).T.cpu().numpy()

    ax.plot(t_axis, nested_s.mean(axis=0),
            color="black", linewidth=1.4, linestyle="--", zorder=2,
            label="Nested - Static")

    # ── Nested heuristic CVaR for power03 (dynamic) actor ─────────────────
    states_d_np = _load(data_dir, alpha_label, "power03", "states.npy")[:, :n_paths, :]
    states_d    = torch.tensor(states_d_np, dtype=torch.float32, device=device)

    nested_d = np.zeros((n_paths, T))
    with torch.no_grad():
        for g in range(n_groups):
            gs, ge = g * group_size, (g + 1) * group_size
            nested_d[:, gs:ge] = nested_critics_dynamic[g](states_d[gs:ge]).T.cpu().numpy()

    ax.plot(t_axis, nested_d.mean(axis=0),
            color=colors[5], linewidth=1.4, linestyle="--", zorder=2,
            label="Nested - Power")

    # ── Legend ─────────────────────────────────────────────────────────────
    from matplotlib.lines import Line2D as _L2D
    leg1 = ax.legend(
        handles=ax.lines[:6], labels=list(scoring_display.values()),
        title="Scoring Function | Dynamic Risk Model",
        frameon=False, ncol=1, loc="upper right",
    )
    ax.add_artist(leg1)
    extra_handles = [
        _L2D([0], [0], color="black",   lw=1.4, linestyle="--"),
        _L2D([0], [0], color=colors[5], lw=1.4, linestyle="--"),
    ]
    ax.legend(
        handles=extra_handles,
        labels=["Nested CVaR - Static actor", "Nested CVaR - Power actor"],
        frameon=False, loc="upper right", bbox_to_anchor=(1, 0.55),
    )

    ax.set_xlabel("Time (years)")
    ax.set_ylabel("Dynamic CVaR Risk")
    _style_ax(ax)

    plt.tight_layout()
    _save(fig, save_dir, "DynamicRiskComparison")
    plt.show()

# ---------------------------------------------------------------------------
# 7. Validation risk  — log files only
# ---------------------------------------------------------------------------

def plot_validation_risk(
    log_files: dict,
    save_dir:  str = ".",
    metric:    str = "CVaR_95%",
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    def _parse(path, key):
        iters, vals, cur = [], [], None
        with open(path) as f:
            for line in f:
                m = re.search(r"Iter (\d+):", line)
                if m:
                    cur = int(m.group(1))
                c = re.search(rf"{key}=([-\d.]+)", line)
                if c and cur is not None:
                    iters.append(cur); vals.append(float(c.group(1)))
        return iters, vals

    colors = plt.cm.tab10(np.linspace(0, 0.6, 6))[[0, 1]]
    fig, ax = plt.subplots(figsize=(10, 5))

    for (label, path), color in zip(log_files.items(), colors):
        iters, vals = _parse(path, metric)
        ax.plot(iters, vals, marker="o", markersize=3, lw=1.8,
                label=label, color=color, alpha=0.9)

    ax.set_xlabel("Iteration", fontsize=12, color="#444444")
    ax.set_ylabel("Validation Dynamic CVaR Risk", fontsize=12, color="#444444")
    _style_ax(ax)
    ax.legend(frameon=False, fontsize=10, loc="upper right", labelcolor="#444444")

    plt.tight_layout()
    _save(fig, save_dir, "validation_risk")
    plt.show()

# ---------------------------------------------------------------------------
# 7. Validation Dynamic
# ---------------------------------------------------------------------------


def plot_validation_risk(
    log_files: dict,
    save_dir:  str = ".",
    metric:    str = "CVaR_95%",
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    def _parse(path, key):
        iters, vals, cur = [], [], None
        with open(path) as f:
            for line in f:
                m = re.search(r"Iter (\d+):", line)
                if m:
                    cur = int(m.group(1))
                c = re.search(rf"{key}=([-\d.]+)", line)
                if c and cur is not None:
                    iters.append(cur); vals.append(float(c.group(1)))
        return iters, vals

    _remap = lambda k: k.replace("bounded", "").replace("shift", "modified").strip()
    log_files = {_remap(k): v for k, v in log_files.items()}

    colors = plt.cm.tab10(np.linspace(0, 0.6, 6))[[0, 1]]
    fig, ax = plt.subplots(figsize=(10, 5))

    for (label, path), color in zip(log_files.items(), colors):
        iters, vals = _parse(path, metric)
        ax.plot(iters, vals, marker="o", markersize=3, lw=1.8,
                label=label, color=color, alpha=0.9)

    ax.set_xlabel("Iteration", fontsize=12, color="#444444")
    ax.set_ylabel("Validation Dynamic CVaR Risk", fontsize=12, color="#444444")
    _style_ax(ax)
    ax.legend(frameon=False, fontsize=10, loc="upper right", labelcolor="#444444")

    plt.tight_layout()
    _save(fig, save_dir, "validation_risk")
    plt.show()

# ---------------------------------------------------------------------------
# 8. Initial dynamic CVaR
# ---------------------------------------------------------------------------

def plot_initial_dynamic_cvar(
    log_files:               dict,
    alpha_label:             str = "alpha95",
    data_dir:                str = "content/data",
    env                          = None,
    CriticCVaR                   = None,
    nested_ckpt_shift_path:  str = "NestedCritics/critic_checkpoint_epoch4.pt",
    nested_ckpt_noshift_path:str = "NestedCritics/critic_checkpoint_noshift_epoch4.pt",
    save_dir:                str = ".",
    n_groups:                int = 18,
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    device     = env.device
    group_size = env.T_days // n_groups

    def _parse_vearly(path):
        iters, vals, cur = [], [], None
        with open(path) as f:
            for line in f:
                m = re.search(r"Iter (\d+):", line)
                if m:
                    cur = int(m.group(1))
                c = re.search(r"V_early=([-\d.]+)", line)
                if c and cur is not None:
                    iters.append(cur); vals.append(float(c.group(1)))
        return iters, vals

    def _nested_t0(ckpt_path, states_t0):
        ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
        critics = torch.nn.ModuleList([
            CriticCVaR(env.state_dim, group_size, hidden_dim=64, head_dim=64, device=device)
            for _ in range(n_groups)
        ])
        for g in range(n_groups):
            critics[g].load_state_dict(ckpt["critics"][g])
            critics[g].to(device).eval()

        with torch.no_grad():
            states_in = states_t0.unsqueeze(0).expand(group_size, -1, -1)
            v0 = critics[0](states_in)
            val = v0.mean().item()
        return val

    colors = plt.cm.tab10(np.linspace(0, 0.6, 6))[[0, 1]]
    color_noshift, color_shift = colors

    fig, ax = plt.subplots(figsize=(10, 5))

    for (label, path), color in zip(log_files.items(), colors):
        iters, vals = _parse_vearly(path)
        ax.plot(iters, vals, marker="o", markersize=3, lw=1.8,
                label=label, color=color, alpha=0.9)

    states_shift   = torch.tensor(
        _load(data_dir, alpha_label, "power03", "states.npy")[0],
        dtype=torch.float32, device=device
    )
    states_noshift = torch.tensor(
        _load(data_dir, alpha_label, "static", "states.npy")[0],
        dtype=torch.float32, device=device
    )

    nested_shift   = _nested_t0(nested_ckpt_shift_path,   states_shift)
    nested_noshift = _nested_t0(nested_ckpt_noshift_path, states_noshift)

    ax.axhline(nested_noshift, color=color_noshift, lw=1.8, linestyle="--", label="Nested", zorder=5)
    ax.axhline(nested_shift,   color=color_shift,   lw=1.8, linestyle="--", label="Nested", zorder=5)

    ax.set_xlabel("Iteration", fontsize=12, color="#444444")
    ax.set_ylabel("Training Initial Dynamic CVaR Risk", fontsize=12, color="#444444")
    _style_ax(ax)
    ax.legend(frameon=False, fontsize=10, loc="upper right", labelcolor="#444444")

    plt.tight_layout()
    _save(fig, save_dir, "InitialDynamicCVaR")
    plt.show()


def plot_actor_critic_loss(
    log_files: dict,
    save_dir:  str = ".",
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    def _parse(path, key):
        iters, vals, cur = [], [], None
        with open(path) as f:
            for line in f:
                m = re.search(r"Iter (\d+):", line)
                if m:
                    cur = int(m.group(1))
                c = re.search(rf"{key}=([-\d.]+)", line)
                if c and cur is not None:
                    iters.append(cur); vals.append(float(c.group(1)))
        return iters, vals


    colors = plt.cm.tab10(np.linspace(0, 0.6, 6))[[0, 1]]
    fig, axes = plt.subplots(1, 2, figsize=(18, 5))

    for ax, (loss_key, ylabel) in zip(axes, [
        ("critic_loss", "Mean Critic Loss"),
        ("actor_loss",  "Mean Actor Loss"),
    ]):
        for (label, path), color in zip(log_files.items(), colors):
            iters, vals = _parse(path, loss_key)
            ax.plot(iters, vals, marker="o", markersize=3, lw=1.8,
                    label=label, color=color, alpha=0.9)
        ax.set_xlabel("Iteration", fontsize=12, color="#444444")
        ax.set_ylabel(ylabel, fontsize=12, color="#444444")
        _style_ax(ax)
        ax.legend(frameon=False, fontsize=10, loc="upper right", labelcolor="#444444")

    plt.tight_layout()
    _save(fig, save_dir, "ALCL")
    plt.show()


def plot_mean_action(
    log_files: dict,
    save_dir:  str = ".",
) -> None:
    plt.rcParams.update({"font.family": "serif", "mathtext.fontset": "cm"})

    def _parse(path):
        iters, vals, cur = [], [], None
        with open(path) as f:
            for line in f:
                m = re.search(r"Iter (\d+):", line)
                if m:
                    cur = int(m.group(1))
                c = re.search(r"mean_action=([-\d.]+)", line)
                if c and cur is not None:
                    iters.append(cur); vals.append(float(c.group(1)))
        return iters, vals

    _remap = lambda k: k.replace("bounded", "").replace("shift", "modified").strip()
    log_files = {_remap(k): v for k, v in log_files.items()}

    colors = plt.cm.tab10(np.linspace(0, 0.6, 6))[[0, 1]]
    fig, ax = plt.subplots(figsize=(8, 5))

    for (label, path), color in zip(log_files.items(), colors):
        iters, vals = _parse(path)
        ax.plot(iters, vals, marker="o", markersize=3, lw=1.8,
                label=label, color=color, alpha=0.9)

    ax.set_xlabel("Iteration", fontsize=12, color="#444444")
    ax.set_ylabel("Mean Action", fontsize=12, color="#444444")
    _style_ax(ax)
    ax.legend(frameon=False, fontsize=10, loc="upper right", labelcolor="#444444")

    plt.tight_layout()
    _save(fig, save_dir, "mean_action")
    plt.show()
